### PR TITLE
Solution for casper.test property is not available

### PR DESCRIPTION
**Pull request by pauljeter**
Found this solution when I got the same error after upgrading PhantomCss and Caperjs.
https://github.com/danbroooks/gulp-phantomcss/issues/4

### CODE REVIEW

**Comment by pauljeter** [comment]
BTW, nice to see the recent activity. I found your plugin about a week ago and forked to start updating. You have already updated and refactored most of what I was doing my self.

**Comment by pauljeter** [comment]
What are your plans for releasing 0.1.0 to npm?

**Comment by danbroooks** [comment]
0.1.0 is now published, includes this fix. Thanks!

**Comment by pauljeter** [comment]
Nice!

**Pull request merged**
